global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'federate'
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]': ['{job="ticketing-api-gateway"}']
    static_configs:
      - targets: ['host.docker.internal:9091', 'host.docker.internal:9092']